### ISSUE TITLE
CSS minify issue

### ISSUE THREAD

**Issue by karanhub** [bitExpert/eclipse-yuicompressor#5]
Hello!
i am using eclipse yuicompressor to minify css. but found a problem.
if there is code something  like this : 
@media (min-width : 1200px) and (max-width : 1600px) {}
then its minified as : 
@media(min-width :1200px) and(max-width:1600px){}
and its not working in browsers because there is no space after 'and' 
please allow space after 'and' so media style will work in browsers.

**Comment by shochdoerfer** [comment]
First of all thanks for using this plugin. The issue most likely comes from the [yuicompressor](https://github.com/yui/yuicompressor/downloads) library which has it's last release in October 2012. Thus we cannot fix the problem in the eclipse plugin - which basically just calls the respective yuicompressor methods.
